version: '3.7'
networks:
  app:
    driver: bridge
services:
  mainDB:
    image: postgres:latest
    container_name: mainDB
    ports:
      - 5100:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - E:\arhive\Web\adviser\BackEnd\DataBases\Main\Data:/var/lib/postgresql/data
      - E:\arhive\Web\adviser\BackEnd\DataBases\Main\Init:/docker-entrypoint-initdb.d
    # networks:
    #   - app

  web:
    image: main:latest
    container_name: main
    # expose: # укажем контейнеру, чтобы только слушал порт и не отдавал ничего наружу. только nginx'y
    #   - "5000"
    # networks:
    #   - app
    ports:
      - 5000:5000
    depends_on:
      - mainDB
