version: '3.7'

services:
  mainDB:
    image: postgres:latest
    container_name: mainDB
    ports:
      - 5100:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - E:\arhive\Web\adviser\BackEnd\DataBases\Main\Data:/var/lib/postgresql/data
      - E:\arhive\Web\adviser\BackEnd\DataBases\Main\Init:/docker-entrypoint-initdb.d

  web:
    image: main:latest
    container_name: main
    environment:
      - ASP_JWTKey=ASPASPASPASPASPASPASP
      - ConnectionString=Server=mainDB;User Id=postgres;Password=postgres;Port=5432;Database=postgres;
    ports:
      - 5000:5000
    depends_on:
      - mainDB
   